name: Lint


on:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - 'src/core/**/*.clj'
      - 'src/core/**/*.cljs'
      - 'src/core/**/*.cljc'
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  clj-kondo:
    name: Lint with clj-kondo
    if: "!(contains(github.event.head_commit.message, 'ci skip') || contains(github.event.head_commit.message, 'skip ci'))"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2022.03.04'
      - name: Lint
        run: |
          clj-kondo --lint src/core
      - name: Discord action job digest notification
        if: always() # Pick up events even if the job fails or is canceled.
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: sarisia/actions-status-discord@v1


  eastwood:
    name: Lint with eastwood
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache gitlibs
        uses: actions/cache@v2
        with:
          path: ~/.gitlibs
          key: ${{ runner.os }}-gitlibs-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-gitlibs-


      - name: Set up jdk 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: 'jdk'


      - name: Set up clojure-cli
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.2.774'


      - name: Run eastwood
        run: clojure -A:eastwood
